### ISSUE TITLE
window平台加固，报错

### ISSUE THREAD

**Issue by lxk123** [kavmors/ApkSheller#3]
D:\demo\ApkSheller>java -jar D:\demo\ApkSheller\ApkSheller.jar D:\As_project\cas
h\apk\jjz.apk
开始加壳工程: jjz
当前工作区: tmp_164231766388818
解压源apk...
I: Using Apktool 2.1.1 on jjz.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Administrator\apktool\framework\1.
apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x01010571
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:57)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:54)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:513)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:264
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
java.io.IOException
        at jcommon.util.Cmd.exec(Cmd.java:26)
        at com.kavmors.apksheller.ShellerProject.extractApk(ShellerProject.java:
146)

**Comment by huangyifei** [comment]
+1
